### PR TITLE
DEBUG: added back missing user options in Argparse object in user_arg…

### PR DESCRIPTION
**Pull request by MasterVexillen**
### Overview
- Debugging user_args --- Added back missing user flags for project and master metadata creation.
- Unified actions to boolean user inputs to "store_true" and fixed logics in corresponding lines in param.

### CODE REVIEW

**Review by MasterVexillen — COMMENTED** [review]
I thought the rot_angle flag should be an essential argument?

**Comment by elainehoml** [comment]
> I thought the pixel_size (MC2) and rot_angle (align) flags should be essential arguments?

Oops, sorry, misunderstood. They initially didn't have any hyphens in the beginning so you couldn't set it but I'll change it back now

**Comment by MasterVexillen** [comment]
> > I thought the pixel_size (MC2) and rot_angle (align) flags should be essential arguments?
> 
> Oops, sorry, misunderstood, changing it back now... was slightly confused since they're essential arguments but there's a bunch of optionals before them too

Ah, arguments with**out** the single/double dash(es) are positional arguments (requisite) and those with are keywords (optional)

**Comment by MasterVexillen** [comment]
> > I thought the pixel_size (MC2) and rot_angle (align) flags should be essential arguments?
> 
> Oops, sorry, misunderstood, changing it back now... was slightly confused since they're essential arguments but there's a bunch of optionals before them too

That's a good point -- I'll move them back in order

**Pull request merged**
